account/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path

from account.views import (
    register_view,
    login_view,
    logout_view,
    account_view,
    search,
    update_view,
)

app_name = 'account'
urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('account/<int:user_id>/', account_view, name='account'),
    path('search/', search, name='search'),
    path('update/<int:pk>/', update_view, name='update'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatapp2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from personal.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('', include('public_chat.urls')),
    path('', home, name='home'),
    path('chat/', include('private_chat.urls')),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friend/urls.py
from django.urls import path

from friend.views import (
    send_friend_request,
    friend_requests,
    accept_friend_request, remove_friend, decline_friend_request, cancel_friend_request, friend_list,

)

app_name = 'friend'

urlpatterns = [
    path('friend_decline/<friend_request_id>', decline_friend_request, name='friend-request-decline'),
    path('friend_list/<user_id>', friend_list, name='friend-list'),
    path('friend_remove/', remove_friend, name='remove-friend'),
    path('friend_request/', send_friend_request, name='friend-request'),
    path('friend_requests/<user_id>/', friend_requests, name='friend-requests'),
    path('friend_request_accept/<friend_request_id>/', accept_friend_request, name='friend-request-accept'),
    path('friend_request_cancel/', cancel_friend_request, name='friend-request-cancel'),
]

private_chat/urls.py
from django.urls import path

from private_chat.views import chat_view

app_name = 'private_chat'

urlpatterns = [
    path('<user1>_<user2>/', chat_view, name='private-chat'),
    #path('<username>/', chat_view, name='private-chat'),
]

account/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models

# Create your models here.

#create a new user
#create a superuser
class MyAccountManager(BaseUserManager):

    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')
        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

def get_profile_image_path(self, *args, **kwargs):
    #print('aaaaaaaaaaaaaaaaaaaaaa', args)
    return f'profile_images/{self.pk}/{self.profile_image}' #??
def get_default_profile_image():
    return 'image/default_image.jpg'

class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name='email', max_length=60, unique=True)
    username = models.CharField(max_length=60, unique=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='date joined')
    last_login = models.DateTimeField(auto_now_add=True, verbose_name='last login')
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False) #i overwrite is_.., from AbstractBaseUser
    is_superuser = models.BooleanField(default=False)
    profile_image = models.ImageField(max_length=255, null=True, blank=True, upload_to=get_profile_image_path, default=get_default_profile_image)
    hide_email = models.BooleanField(default=True)

    objects = MyAccountManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def get_profile_image_filename(self):
        return str(self.profile_image)[str(self.profile_image).index(f'profile_images/{self.pk}/'):]

personal/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from account.models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=120, help_text='Required. Add a valid email address', required=True)

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2')

    #validation, when form is submited
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.get(email=email)
        except Exception as e:
            return email
        raise forms.ValidationError(f'Email {email} is already in use!')

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Account.objects.get(username=username)
        except Exception as e:
            return username
        raise forms.ValidationError(f'Email {username} is already in use!')

class LoginForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")


class UpdateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('email', 'username', 'profile_image', 'hide_email')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Exception as e:
            return email
        raise forms.ValidationError(f'Email {email} is already in use!')

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Exception as e:
            return username
        raise forms.ValidationError(f'Email {username} is already in use!')

    def save(self, commit=True):
        account = super(UpdateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email'].lower()
        account.profile_image = self.cleaned_data['profile_image']
        account.hide_email = self.cleaned_data['hide_email']
        if commit:
            account.save()
        return account

account/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from account.forms import RegistrationForm, LoginForm, UpdateForm
from account.models import Account
from friend.friend_request_status import FriendRequestStatus
from friend.models import FriendList, FriendRequest
from friend.utils import get_friend_request_or_false


def register_view(request, *args, **kwargs):
     user = request.user
     if user.is_authenticated:
         return HttpResponse(f'You are already authenticated as {user.email}!')

     context = {}

     if request.method == 'POST':
         form = RegistrationForm(request.POST)
         if form.is_valid():
             form.save()
             email = form.cleaned_data.get('email').lower()
             raw_password = form.cleaned_data.get('password1')
             account = authenticate(email=email, password=raw_password)
             login(request, account)
             destination = kwargs.get('next')
             if destination:
                 return redirect(destination)
             else:
                 return redirect('home')
         else:
             context['registration_form'] = form

     return render(request, 'personal/register.html', context)


def login_view(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        return HttpResponse(f'You are already authenticated as {user.email}!')

    context = {}
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email').lower()
            raw_password = form.cleaned_data.get('password')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            destination = kwargs.get('next')
            if destination:
                return redirect(destination)
            else:
                return redirect('home')
        else:
            context['login_form'] = form

    return render(request, 'personal/login.html', context)

def logout_view(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        logout(request)
    return redirect('home')


def account_view(request, *args, **kwargs):
    '''
    is_self - boolean
    is_friend

    -1: NO_REQUEST_SENT
    0: THEM_SENT_TO_YOU
    1: YOU_SENT_TO_THEM
    '''
    context = {}
    user_id = kwargs.get("user_id")
    try:
        account = Account.objects.get(pk=user_id)
    except:
        return HttpResponse("Something went wrong.")
    if account:
        context['id'] = account.id
        context['username'] = account.username
        context['email'] = account.email
        context['profile_image'] = account.profile_image.url
        context['hide_email'] = account.hide_email

        try:
            friend_list = FriendList.objects.get(user=account)
        except FriendList.DoesNotExist:
            friend_list = FriendList(user=account)
            friend_list.save()
        friends = friend_list.friends.all()
        context['friends'] = friends

        # Define template variables
        is_self = True
        is_friend = False
        request_sent = FriendRequestStatus.NO_REQUEST_SENT.value  # range: ENUM -> friend/friend_request_status.FriendRequestStatus
        friend_requests = None
        user = request.user
        if user.is_authenticated and user != account:
            is_self = False
            if friends.filter(pk=user.id):
                is_friend = True
            else:
                is_friend = False
                # CASE1: Request has been sent from THEM to YOU: FriendRequestStatus.THEM_SENT_TO_YOU
                if get_friend_request_or_false(sender=account, receiver=user) != False:
                    request_sent = FriendRequestStatus.THEM_SENT_TO_YOU.value
                    context['pending_friend_request_id'] = get_friend_request_or_false(sender=account, receiver=user).id
                # CASE2: Request has been sent from YOU to THEM: FriendRequestStatus.YOU_SENT_TO_THEM
                elif get_friend_request_or_false(sender=user, receiver=account) != False:
                    request_sent = FriendRequestStatus.YOU_SENT_TO_THEM.value
                # CASE3: No request sent from YOU or THEM: FriendRequestStatus.NO_REQUEST_SENT
                else:
                    request_sent = FriendRequestStatus.NO_REQUEST_SENT.value

        elif not user.is_authenticated:
            is_self = False
        else:
            try:
                friend_requests = FriendRequest.objects.filter(receiver=user, is_active=True)
            except:
                pass

        # Set the template variables to the values
        context['is_self'] = is_self
        context['is_friend'] = is_friend
        context['request_sent'] = request_sent
        context['friend_requests'] = friend_requests
        context['BASE_URL'] = settings.BASE_URL
        return render(request, "personal/account.html", context)

def search(request, *args, **kwargs):
    context = {}
    accounts = []
    user = request.user

    if request.method == 'GET':
        username = request.GET.get('search')
        status = Account.objects.filter(username__icontains=username)  # returns a list
        if user.is_authenticated:
            auth_user_friends = FriendList.objects.get(user=user)
            # [(account1, True/False), (account2, True/False)...]
            # True if we are friends
            for account in status:
                if account in auth_user_friends.friends.all():
                    accounts.append((account, True))
                else:
                    accounts.append((account, False))
        else:
            for account in status:
                accounts.append((account, False))
        context['accounts'] = accounts
    return render(request, "personal/search.html", context)


def update_view(request, *args, **kwargs):
    pk = kwargs['pk']
    try:
        account = Account.objects.get(pk=pk)
    except Account.DoesNotExist:
        raise HttpResponse("Something went wrong!")

    if request.user.pk != account.pk:
        return HttpResponse("You cannot edit someone elses profile!")

    context = {}
    if request.method == 'POST':
        form = UpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            account.profile_image.delete()
            form.save()
            return redirect('account:account', user_id=pk)
        else:
            form = UpdateForm(
                request.POST,
                instance=request.user,
                initial= {
                    'id': account.pk,
                    'email': account.email,
                    'username': account.username,
                    'profile_image': account.profile_image,
                    'hide_email': account.hide_email,
                }
            )
    else:
        form = UpdateForm(
            request.POST,
            initial={
                'id': account.pk,
                'email': account.email,
                'username': account.username,
                'profile_image': account.profile_image,
                'hide_email': account.hide_email,
            }
        )

    context['form'] = form
    context['DATA_UPLOAD_MAX_MEMORY_SIZE'] = settings.DATA_UPLOAD_MAX_MEMORY_SIZE

    return render(request, 'personal/update_account.html', context)

personal/views.py
from django.shortcuts import render

# Create your views here.
from public_chat.forms import ComposeForm


def home(request):
    #return render(request, 'personal/home.html', {})
    context = {}
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ComposeForm(request.POST)
            if form.is_valid():
                context['user'] = request.user
                # ChatMessage.objects.create(user=request.user, thread=thread, message=message)
        else:
            form = ComposeForm()

        context['form'] = form
        context['user'] = request.user
    return render(request, 'public_chat/room.html', {})

personal/templates/personal/account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
	}
	.field-heading{
		color: var(--secondary-text-color);
	}
	.icon-container:hover {
		opacity: 0.3;
		cursor: pointer;
	}
	.friends-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.person-add-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.friend-text{
		font-weight: 500;
		color: black;
	}
	.friends-btn{
		background-color: #cccccc;
		border-color: #cccccc;
		color: #000;
		font-weight: 500;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.card{
		border-radius: 12px;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request{
		color: green;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request{
		color: red;
	}
	.message-btn-text{
		font-weight: 500;
	}
</style>

<div class="container-fluid">
	<div class="d-flex flex-row justify-content-center flex-wrap align-items-start">

		<div class="card profile-card m-2">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="image-container mx-auto mb-4">
		  			<img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image" id="id_profile_image" src="{{profile_image}}">
		  		</div>
		  		<p class="mt-4 mb-1 field-heading">Email</p>
		  		{%  if is_self %}
		  			<h5>{{email}}</h5>
		  		{% else %}
		  			{% if hide_email %}
			  			<h5>**********</h5>
			  		{% else %}
			  			<h5>{{email}}</h5>
			  		{% endif %}
			  	{% endif %}
		  		<p class="mt-4 mb-1 field-heading">Username</p>
		  		<h5>{{username}}</h5>

		  		<!-- If Auth user is viewing their own profile -->
		  		{% if is_self %}
		  		<a  class="mt-4 btn btn-primary" href="{% url 'account:update' pk=id %}">Update</a>
				<div class="d-flex flex-column mt-4">
					<a class="m-auto" href="{% url 'password_change' %}">Change password</a>
				</div>
		  		{% endif %}
		  	</div>
		  </div>
		</div>

		{% if request.user.is_authenticated %}
		<div class="d-flex flex-column mb-4">

			<!-- THEM to YOU -->
			{% if request_sent == 0 %}
			<div class="card m-2 p-4">
				<div class="d-flex flex-row align-items-center">
					<span class="friend-text align-items-center mr-2">Accept Friend Request</span>
					<span id="id_cancel_{{id}}" class="decline-friend-request material-icons p-1" onclick='triggerDeclineFriendRequest("{{pending_friend_request_id}}")'>cancel</span>
  					<span id="id_confirm_{{id}}" class="confirm-friend-request material-icons p-1" onclick='triggerAcceptFriendRequest("{{pending_friend_request_id}}")'>check</span>
				</div>
			</div>
			{% endif %}

			<div class="card m-2 px-4 pb-4">
				<!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
				{% if is_friend == False and is_self == False %}
						<!-- You sent them a request -->
						{% if request_sent == 1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-danger" id="id_cancel_friend_request_btn">
								Cancel Friend Request
							</button>
						</div>
						{% endif %}
						<!-- No requests have been sent -->
						{% if request_sent == -1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-primary" id="id_send_friend_request_btn">
								Send Friend Request
							</button>
						</div>
						{% endif %}
				{% endif %}


				{% if is_friend %}
					<div class="dropdown pt-4 m-auto">
						<button class="btn btn-secondary dropdown-toggle friends-btn" type="button" id="id_friends_toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Friends
						</button>
						<div class="dropdown-menu" aria-labelledby="id_friends_toggle">
							<a class="dropdown-item" href="" onclick="removeFriend('{{id}}', onFriendRemoved)">Unfriend</a>
						</div>
                        <button class="btn btn-primary" id="id_unfriend_btn">
                            Unfriend
                        </button>
					</div>
				{% endif %}

				<!-- Friend list link -->
		  		<div class="d-flex flex-column pt-4">
					<a href="{% url 'friend:friend-list' user_id=id %}">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="material-icons mr-2 friends-icon">contact_page</span><span class="friend-text">Friends ({{friends|length}})</span>
						</div>
					</a>
				</div>

			</div>

			{% if friend_requests %}
			<div class="card m-2 px-4 pb-4">
				<!-- Friend requests -->
		  		<div class="d-flex flex-column pt-4">
					<a href="{% url 'friend:friend-requests' user_id=id %}">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="material-icons mr-2 person-add-icon">person_add</span><span class="friend-text">Friend Requests ({{friend_requests|length}})</span>
						</div>
					</a>
				</div>
			</div>
			{% endif %}

			{% if is_friend %}
				<div class="d-flex flex-row align-items-center btn btn-primary m-2 px-4" onclick="createOrReturnPrivateChat('{{ username }}', '{{ user }}')">
					<span class="material-icons m-auto">
					message
					</span>
					<span class="message-btn-text m-auto pl-2">Message</span>
				</div>
			{% endif %}

		</div>
		{% endif %}


	</div>
</div>


<script type="text/javascript">

    function createOrReturnPrivateChat(user1, user2){
        var url = "{% url 'private_chat:private-chat' user1=53252623623632623 user2=10000000020 %}".replace("53252623623632623", user2).replace("10000000020", user1)
        var win = window.open(url, "_blank")
        win.focus()
    }

	function onFriendRequestSent(){
		location.reload();
	}

	function onFriendRequestCancelled(){
		location.reload();
	}

	function onFriendRemoved(){
		location.reload();
	}

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}

	var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
	if (sendFriendRequestBtn != null){
		sendFriendRequestBtn.addEventListener("click", function(){
			sendFriendRequest("{{id}}", onFriendRequestSent)
		})
	}

	var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
	if(cancelFriendRequestBtn != null){
		cancelFriendRequestBtn.addEventListener("click", function(){
			cancelFriendRequest("{{id}}", onFriendRequestCancelled)
		})
	}

	var removeFriendBtn = document.getElementById("id_unfriend_btn")
	if (removeFriendBtn != null){
		removeFriendBtn.addEventListener("click", function(){
			removeFriend("{{id}}", onFriendRemoved)
		})
	}

	function triggerAcceptFriendRequest(friend_request_id){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}

</script>

{% include 'friend/send_friend_request.html' %}
{% include 'friend/accept_friend_request.html' %}
{% include 'friend/decline_friend_request.html' %}
{% include 'friend/cancel_friend_request.html' %}
{% include 'friend/remove_friend.html' %}

{% endblock content %}

personal/templates/personal/base_css.html
<style type="text/css">
	head{
        font-family: "Segoe UI";
		font-weight: 380;
	}
	footer{
		font-family: "Segoe UI";
		font-weight: 380;
	}
	body{
		background-color: #f2f2f2;
		font-family: "Segoe UI";
		font-weight: 380;
	}

	:root{
		--main-background-color: #f2f2f2;
		--dark-background-color: #a2a2a2;
		--secondary-text-color: #808080;
		--light-primary-text-color: #0080ff;
	}




</style>

personal/templates/personal/base_js.html
<script type="text/javascript">

</script>

personal/templates/personal/header.html
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<!-- Header -->
<div class="d-flex flex-column flex-lg-row p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

	<!-- MEDIUM+ SCREENS -->
	<div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
		<h5 class="mr-3 font-weight-normal justify-content-start">
			<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		</h5>
		<form class="search-bar justify-content-start" method="GET" action="{% url 'account:search' %}">
			<input type="text" class="form-control" name="search" id="id_q_small" placeholder="Search...">
            <input class="btn btn-primary float-right" id="button-search" type="submit" value="Go!">
		</form>

		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
                    <div class="dropdown">
                      <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{ user.profile_image.url }}" width="40" height="40">
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                          <button class="dropdown-item" type="button"><a href="{% url 'account:account' user_id=request.user.id %}">Account</a></button>
                          <button class="dropdown-item" type="button"><a href="{% url 'account:logout' %}">Log out</a></button>
                        <button class="dropdown-item" type="button">Another action</button>
                        <button class="dropdown-item" type="button">Something else here</button>
                      </div>
                    </div>


{#                    <div class="dropdown">#}
{#                        <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">#}
{#                         <img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{ user.profile_image.url }}" width="40" height="40">#}
{#                           <span class="caret"></span>#}
{#                        </button>#}
{#                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">#}
{#                          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Menu item 1</a></li>#}
{#                          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Menu item 2</a></li>#}
{#                          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Menu item 3</a></li>#}
{#                          <li role="presentation" class="divider"></li>#}
{#                          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Menu item 4</a></li>#}
{#                        </ul>#}
{#                    </div>#}
				{% else %}
					<a class="p-2 text-dark" href="{% url 'account:login' %}">Login</a>
					<a class="btn btn-outline-primary" href="{% url 'account:register' %}">Register</a>
				{% endif %}
			</nav>
		</div>
	</div>
	<!-- END MEDIUM+ SCREENS -->

	<!-- SMALL SCREENS -->
	<div class="d-flex d-md-none flex-column my-auto align-items-center">
		<h5 class="font-weight-normal">
		<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		</h5>
		<form class="search-bar justify-content-start" method="GET" action="{% url 'account:search' %}">
			<input type="text" class="form-control" name="search" id="id_q_small" placeholder="Search...">
            <input class="btn btn-primary" id="button-search" type="submit" value="Go!">
		</form>
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
				<div class="dropdown dropleft p-2 mt-2">
					<div class="d-flex flex-row">
						<div class="btn-group dropleft">
							<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{ user.profile_image.url }}"  width="40" height="40">
							<div class="dropdown-menu" aria-labelledby="id_profile_links">
								<a class="dropdown-item" href="#">Account</a>
								<a class="dropdown-item" href="#">Logout</a>
							</div>
						</div>
					</div>
				</div>
				{% else %}
					<a class="p-2 text-dark" href="#">Login</a>
					<a class="btn btn-outline-primary m-2" href="#">Register</a>
				{% endif %}
			</nav>
	  	</div>
	</div>
	<!-- END SMALL SCREENS -->
</div>